Avoid conflict between pango warn variable and libasync warn.
Recent gcc don't like the variable named warn in pango.h if warn
is the libasync warnobj.  It complains:

    /usr/local/include/pango-1.0/pango/pango-utils.h:54: error: expected `,' or `...' before '(' token

Observed at least on FreeBSD 6.2 with gcc 3.4.6 and FC 7 with gcc 4.1.2.

To work around this, include the gtk header files first, before any
header files that might include async.h.

Problem first reported by "Brown, Adam J" <ajbrowc@essex.ac.uk>.
Solution suggested by Max Krohn <krohn@mit.edu>.